// This file is auto-generated by @hey-api/openapi-ts

export const AnalyticsOverviewSchema = {
    properties: {
        submitted_problems: {
            type: 'integer',
            title: 'Submitted Problems'
        },
        published_problems: {
            type: 'integer',
            title: 'Published Problems'
        },
        claimed_problems: {
            type: 'integer',
            title: 'Claimed Problems'
        },
        piloting_problems: {
            type: 'integer',
            title: 'Piloting Problems'
        },
        solved_problems: {
            type: 'integer',
            title: 'Solved Problems'
        },
        proposed_projects: {
            type: 'integer',
            title: 'Proposed Projects'
        },
        active_projects: {
            type: 'integer',
            title: 'Active Projects'
        },
        completed_projects: {
            type: 'integer',
            title: 'Completed Projects'
        },
        problem_to_claim_rate: {
            type: 'number',
            title: 'Problem To Claim Rate'
        },
        claim_to_solved_rate: {
            type: 'number',
            title: 'Claim To Solved Rate'
        }
    },
    type: 'object',
    required: ['submitted_problems', 'published_problems', 'claimed_problems', 'piloting_problems', 'solved_problems', 'proposed_projects', 'active_projects', 'completed_projects', 'problem_to_claim_rate', 'claim_to_solved_rate'],
    title: 'AnalyticsOverview'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CommentSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Text'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['text', 'problem_id', 'user_id'],
    title: 'Comment'
} as const;

export const CommentCreateSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Text'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Text'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['text', 'id', 'problem_id', 'user_id', 'created_at'],
    title: 'CommentPublic'
} as const;

export const CommentsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CommentsPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        payload: {
            additionalProperties: true,
            type: 'object',
            title: 'Payload'
        },
        read_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Read At'
        },
        delivery_status: {
            type: 'string',
            title: 'Delivery Status'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        },
        delivery_error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivery Error'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'type', 'payload', 'delivery_status', 'created_at'],
    title: 'NotificationPublic'
} as const;

export const NotificationReadRequestSchema = {
    properties: {
        notification_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Notification Ids'
        }
    },
    type: 'object',
    title: 'NotificationReadRequest'
} as const;

export const NotificationsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/NotificationPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        unread_count: {
            type: 'integer',
            title: 'Unread Count'
        }
    },
    type: 'object',
    required: ['data', 'count', 'unread_count'],
    title: 'NotificationsPublic'
} as const;

export const PresignRequestSchema = {
    properties: {
        kind: {
            type: 'string',
            title: 'Kind'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        problem_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Problem Id'
        }
    },
    type: 'object',
    required: ['kind', 'content_type', 'size'],
    title: 'PresignRequest'
} as const;

export const PresignResponseSchema = {
    properties: {
        upload_url: {
            type: 'string',
            title: 'Upload Url'
        },
        object_key: {
            type: 'string',
            title: 'Object Key'
        },
        method: {
            type: 'string',
            title: 'Method',
            default: 'PUT'
        }
    },
    type: 'object',
    required: ['upload_url', 'object_key'],
    title: 'PresignResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProblemCreateSchema = {
    properties: {
        raw_text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 5000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Text'
        },
        raw_audio_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Audio Key'
        },
        region_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region Id'
        }
    },
    type: 'object',
    title: 'ProblemCreate'
} as const;

export const ProblemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        sector_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sector Id'
        },
        region_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region Id'
        },
        raw_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Text'
        },
        raw_audio_key: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Audio Key'
        },
        transcript: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transcript'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        structured_desc: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Structured Desc'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        severity_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Severity Score'
        },
        vote_count: {
            type: 'integer',
            title: 'Vote Count'
        },
        duplicate_of: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duplicate Of'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'author_id', 'status', 'vote_count', 'created_at', 'updated_at'],
    title: 'ProblemPublic'
} as const;

export const ProblemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProblemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProblemsPublic'
} as const;

export const ProjectCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        pitch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pitch'
        },
        repo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo Url'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ProjectCreate'
} as const;

export const ProjectMilestoneCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'todo'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ProjectMilestoneCreate'
} as const;

export const ProjectMilestonePublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: 'Status',
            default: 'todo'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        sort_order: {
            type: 'integer',
            title: 'Sort Order',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'project_id', 'created_at'],
    title: 'ProjectMilestonePublic'
} as const;

export const ProjectMilestoneUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sort Order'
        }
    },
    type: 'object',
    title: 'ProjectMilestoneUpdate'
} as const;

export const ProjectMilestonesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectMilestonePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectMilestonesPublic'
} as const;

export const ProjectPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        pitch: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pitch'
        },
        repo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo Url'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        problem_id: {
            type: 'string',
            format: 'uuid',
            title: 'Problem Id'
        },
        lead_id: {
            type: 'string',
            format: 'uuid',
            title: 'Lead Id'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'problem_id', 'lead_id', 'status', 'created_at', 'updated_at'],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateCreateSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 3000,
            minLength: 1,
            title: 'Text'
        },
        media_keys: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Media Keys'
        }
    },
    type: 'object',
    required: ['text'],
    title: 'ProjectUpdateCreate'
} as const;

export const ProjectUpdatePublicSchema = {
    properties: {
        text: {
            type: 'string',
            maxLength: 3000,
            minLength: 1,
            title: 'Text'
        },
        media_keys: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Media Keys'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        author_id: {
            type: 'string',
            format: 'uuid',
            title: 'Author Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['text', 'id', 'project_id', 'author_id', 'created_at'],
    title: 'ProjectUpdatePublic'
} as const;

export const ProjectUpdatesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectUpdatePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectUpdatesPublic'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProjectsPublic'
} as const;

export const ReviewCreateSchema = {
    properties: {
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text'
        }
    },
    type: 'object',
    required: ['rating'],
    title: 'ReviewCreate'
} as const;

export const ReviewPublicSchema = {
    properties: {
        rating: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Rating'
        },
        text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        reviewer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Reviewer Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['rating', 'id', 'project_id', 'reviewer_id', 'created_at'],
    title: 'ReviewPublic'
} as const;

export const TelegramAuthStartRequestSchema = {
    properties: {
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        client: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client',
            default: 'web'
        }
    },
    type: 'object',
    title: 'TelegramAuthStartRequest'
} as const;

export const TelegramAuthStartResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        deep_link: {
            type: 'string',
            title: 'Deep Link'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: ['session_id', 'deep_link', 'expires_at'],
    title: 'TelegramAuthStartResponse'
} as const;

export const TelegramAuthStatusResponseSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        access_token: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['status'],
    title: 'TelegramAuthStatusResponse'
} as const;

export const TelegramContactVerifyRequestSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        telegram_id: {
            type: 'integer',
            title: 'Telegram Id'
        },
        phone: {
            type: 'string',
            title: 'Phone'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        contact_user_id: {
            type: 'integer',
            title: 'Contact User Id'
        },
        from_user_id: {
            type: 'integer',
            title: 'From User Id'
        }
    },
    type: 'object',
    required: ['token', 'telegram_id', 'phone', 'contact_user_id', 'from_user_id'],
    title: 'TelegramContactVerifyRequest'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        telegram_username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Username'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        region_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region Id'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        reputation: {
            type: 'integer',
            title: 'Reputation',
            default: 0
        },
        tg_linked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tg Linked At'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        telegram_username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Username'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        region_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region Id'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        reputation: {
            type: 'integer',
            title: 'Reputation',
            default: 0
        },
        tg_linked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tg Linked At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        telegram_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Id'
        },
        telegram_username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Telegram Username'
        },
        roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Roles'
        },
        region_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region Id'
        },
        bio: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bio'
        },
        reputation: {
            type: 'integer',
            title: 'Reputation',
            default: 0
        },
        tg_linked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tg Linked At'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;