// This file is auto-generated by @hey-api/openapi-ts

export type AIAnalysisPublic = {
    id: string;
    problem_id: string;
    model: string;
    summary_json: {
        [key: string]: unknown;
    };
    created_at: string;
};

export type AIAnalysisPublics = {
    data: Array<AIAnalysisPublic>;
    count: number;
};

export type AnalyticsOverview = {
    submitted_problems: number;
    ai_processing_problems: number;
    needs_review_problems: number;
    published_problems: number;
    claimed_problems: number;
    piloting_problems: number;
    solved_problems: number;
    proposed_projects: number;
    active_projects: number;
    completed_projects: number;
    problem_to_claim_rate: number;
    claim_to_solved_rate: number;
};

export type Comment = {
    text: string;
    parent_id?: (string | null);
    id?: string;
    problem_id: string;
    user_id: string;
    created_at?: string;
};

export type CommentCreate = {
    text: string;
    parent_id?: (string | null);
};

export type CommentPublic = {
    text: string;
    parent_id?: (string | null);
    id: string;
    problem_id: string;
    user_id: string;
    created_at: string;
};

export type CommentsPublic = {
    data: Array<CommentPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationPublic = {
    id: string;
    user_id: string;
    type: string;
    payload: {
        [key: string]: unknown;
    };
    read_at?: (string | null);
    delivery_status: string;
    delivered_at?: (string | null);
    delivery_error?: (string | null);
    created_at: string;
};

export type NotificationReadRequest = {
    notification_ids?: Array<(string)>;
};

export type NotificationsPublic = {
    data: Array<NotificationPublic>;
    count: number;
    unread_count: number;
};

export type PresignRequest = {
    kind: string;
    content_type: string;
    size: number;
    problem_id?: (string | null);
};

export type PresignResponse = {
    upload_url: string;
    object_key: string;
    method?: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProblemCreate = {
    raw_text?: (string | null);
    raw_audio_key?: (string | null);
    region_id?: (number | null);
    photo_keys?: Array<(string)>;
};

export type ProblemMediaPublic = {
    id: string;
    problem_id: (string | null);
    kind: string;
    object_key: string;
    url: string;
    created_at: string;
};

export type ProblemMediaPublics = {
    data: Array<ProblemMediaPublic>;
    count: number;
};

export type ProblemMergeRequest = {
    target_problem_id: string;
};

export type ProblemPublic = {
    id: string;
    author_id: string;
    sector_id?: (number | null);
    region_id?: (number | null);
    raw_text?: (string | null);
    raw_audio_key?: (string | null);
    transcript?: (string | null);
    title?: (string | null);
    structured_desc?: ({
    [key: string]: unknown;
} | null);
    status: string;
    severity_score?: (number | null);
    vote_count: number;
    comment_count?: number;
    project_count?: number;
    duplicate_of?: (string | null);
    has_voted?: boolean;
    published_at?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProblemsPublic = {
    data: Array<ProblemPublic>;
    count: number;
};

export type ProjectCreate = {
    title: string;
    pitch?: (string | null);
    repo_url?: (string | null);
};

export type ProjectMilestoneCreate = {
    title: string;
    status?: string;
    due_date?: (string | null);
    sort_order?: number;
};

export type ProjectMilestonePublic = {
    title: string;
    status?: string;
    due_date?: (string | null);
    sort_order?: number;
    id: string;
    project_id: string;
    created_at: string;
};

export type ProjectMilestonesPublic = {
    data: Array<ProjectMilestonePublic>;
    count: number;
};

export type ProjectMilestoneUpdate = {
    title?: (string | null);
    status?: (string | null);
    due_date?: (string | null);
    sort_order?: (number | null);
};

export type ProjectPublic = {
    title: string;
    pitch?: (string | null);
    repo_url?: (string | null);
    id: string;
    problem_id: string;
    lead_id: string;
    status: string;
    created_at: string;
    updated_at: string;
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdateCreate = {
    text: string;
    media_keys?: Array<(string)>;
};

export type ProjectUpdateMediaPublic = {
    object_key: string;
    kind: string;
    url: string;
};

export type ProjectUpdatePublic = {
    text: string;
    media_keys?: Array<(string)>;
    id: string;
    project_id: string;
    author_id: string;
    created_at: string;
    media?: Array<ProjectUpdateMediaPublic>;
};

export type ProjectUpdatesPublic = {
    data: Array<ProjectUpdatePublic>;
    count: number;
};

export type ReviewCreate = {
    rating: number;
    text?: (string | null);
};

export type ReviewPublic = {
    rating: number;
    text?: (string | null);
    id: string;
    project_id: string;
    reviewer_id: string;
    created_at: string;
};

export type ReviewsPublic = {
    data: Array<ReviewPublic>;
    count: number;
};

export type TelegramAuthStartRequest = {
    phone?: (string | null);
    client?: (string | null);
};

export type TelegramAuthStartResponse = {
    session_id: string;
    deep_link: string;
    expires_at: string;
};

export type TelegramAuthStatusResponse = {
    status: string;
    access_token?: (string | null);
    token_type?: string;
    expires_at?: (string | null);
    retry_after_seconds?: (number | null);
};

export type TelegramContactVerifyRequest = {
    token: string;
    telegram_id: number;
    phone: string;
    first_name?: (string | null);
    last_name?: (string | null);
    username?: (string | null);
    contact_user_id: number;
    from_user_id: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    phone?: (string | null);
    telegram_id?: (number | null);
    telegram_username?: (string | null);
    roles?: Array<(string)>;
    region_id?: (number | null);
    bio?: (string | null);
    reputation?: number;
    tg_linked_at?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    phone?: (string | null);
    telegram_id?: (number | null);
    telegram_username?: (string | null);
    roles?: Array<(string)>;
    region_id?: (number | null);
    language?: string;
    bio?: (string | null);
    reputation?: number;
    tg_linked_at?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    phone?: (string | null);
    telegram_id?: (number | null);
    telegram_username?: (string | null);
    roles?: Array<(string)>;
    region_id?: (number | null);
    bio?: (string | null);
    reputation?: number;
    tg_linked_at?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    language?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AnalyticsReadAnalyticsOverviewResponse = (AnalyticsOverview);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaPresignMediaUploadData = {
    requestBody: PresignRequest;
};

export type MediaPresignMediaUploadResponse = (PresignResponse);

export type NotificationsReadNotificationsData = {
    limit?: number;
    skip?: number;
    unreadOnly?: boolean;
};

export type NotificationsReadNotificationsResponse = (NotificationsPublic);

export type NotificationsMarkOneNotificationReadData = {
    notificationId: string;
};

export type NotificationsMarkOneNotificationReadResponse = (NotificationPublic);

export type NotificationsMarkNotificationsReadData = {
    requestBody: NotificationReadRequest;
};

export type NotificationsMarkNotificationsReadResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProblemsCreateProblemData = {
    requestBody: ProblemCreate;
};

export type ProblemsCreateProblemResponse = (ProblemPublic);

export type ProblemsReadProblemsData = {
    limit?: number;
    mine?: boolean;
    q?: (string | null);
    regionId?: (number | null);
    sectorId?: (number | null);
    skip?: number;
    status?: string;
};

export type ProblemsReadProblemsResponse = (ProblemsPublic);

export type ProblemsReadProblemMediaData = {
    problemId: string;
};

export type ProblemsReadProblemMediaResponse = (ProblemMediaPublics);

export type ProblemsReadProblemAnalysesData = {
    problemId: string;
};

export type ProblemsReadProblemAnalysesResponse = (AIAnalysisPublics);

export type ProblemsReadProblemData = {
    problemId: string;
};

export type ProblemsReadProblemResponse = (ProblemPublic);

export type ProblemsPublishProblemData = {
    problemId: string;
};

export type ProblemsPublishProblemResponse = (ProblemPublic);

export type ProblemsArchiveProblemData = {
    problemId: string;
};

export type ProblemsArchiveProblemResponse = (ProblemPublic);

export type ProblemsReanalyzeProblemData = {
    problemId: string;
};

export type ProblemsReanalyzeProblemResponse = (ProblemPublic);

export type ProblemsSolveProblemData = {
    problemId: string;
};

export type ProblemsSolveProblemResponse = (ProblemPublic);

export type ProblemsMergeProblemData = {
    problemId: string;
    requestBody: ProblemMergeRequest;
};

export type ProblemsMergeProblemResponse = (ProblemPublic);

export type ProblemsVoteProblemData = {
    problemId: string;
};

export type ProblemsVoteProblemResponse = (void);

export type ProblemsUnvoteProblemData = {
    problemId: string;
};

export type ProblemsUnvoteProblemResponse = (Message);

export type ProblemsReadCommentsData = {
    limit?: number;
    problemId: string;
    skip?: number;
};

export type ProblemsReadCommentsResponse = (CommentsPublic);

export type ProblemsCreateCommentData = {
    problemId: string;
    requestBody: CommentCreate;
};

export type ProblemsCreateCommentResponse = (Comment);

export type ProjectsCreateClaimData = {
    problemId: string;
    requestBody: ProjectCreate;
};

export type ProjectsCreateClaimResponse = (ProjectPublic);

export type ProjectsReadProjectsData = {
    limit?: number;
    mine?: boolean;
    owner?: boolean;
    problemId?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type ProjectsReadProjectsResponse = (ProjectsPublic);

export type ProjectsReadProjectData = {
    projectId: string;
};

export type ProjectsReadProjectResponse = (ProjectPublic);

export type ProjectsApproveProjectEndpointData = {
    projectId: string;
};

export type ProjectsApproveProjectEndpointResponse = (ProjectPublic);

export type ProjectsRejectProjectEndpointData = {
    projectId: string;
};

export type ProjectsRejectProjectEndpointResponse = (ProjectPublic);

export type ProjectsStartProjectPilotingEndpointData = {
    projectId: string;
};

export type ProjectsStartProjectPilotingEndpointResponse = (ProjectPublic);

export type ProjectsCompleteProjectEndpointData = {
    projectId: string;
    requestBody: ReviewCreate;
};

export type ProjectsCompleteProjectEndpointResponse = (ReviewPublic);

export type ProjectsReadProjectReviewsData = {
    projectId: string;
};

export type ProjectsReadProjectReviewsResponse = (ReviewsPublic);

export type ProjectsReadProjectMilestonesData = {
    projectId: string;
};

export type ProjectsReadProjectMilestonesResponse = (ProjectMilestonesPublic);

export type ProjectsCreateProjectMilestoneData = {
    projectId: string;
    requestBody: ProjectMilestoneCreate;
};

export type ProjectsCreateProjectMilestoneResponse = (ProjectMilestonePublic);

export type ProjectsUpdateProjectMilestoneData = {
    milestoneId: string;
    requestBody: ProjectMilestoneUpdate;
};

export type ProjectsUpdateProjectMilestoneResponse = (ProjectMilestonePublic);

export type ProjectsReadProjectUpdatesData = {
    projectId: string;
};

export type ProjectsReadProjectUpdatesResponse = (ProjectUpdatesPublic);

export type ProjectsCreateProjectUpdateData = {
    projectId: string;
    requestBody: ProjectUpdateCreate;
};

export type ProjectsCreateProjectUpdateResponse = (ProjectUpdatePublic);

export type TelegramAuthStartTelegramAuthData = {
    requestBody: TelegramAuthStartRequest;
};

export type TelegramAuthStartTelegramAuthResponse = (TelegramAuthStartResponse);

export type TelegramAuthTelegramAuthStatusData = {
    sessionId: string;
};

export type TelegramAuthTelegramAuthStatusResponse = (TelegramAuthStatusResponse);

export type TelegramAuthMarkStartData = {
    sessionId: string;
    xTelegramWebhookSecret?: (string | null);
};

export type TelegramAuthMarkStartResponse = (TelegramAuthStatusResponse);

export type TelegramAuthVerifyContactData = {
    requestBody: TelegramContactVerifyRequest;
    xTelegramWebhookSecret?: (string | null);
};

export type TelegramAuthVerifyContactResponse = (TelegramAuthStatusResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsReadinessCheckResponse = ({
    [key: string]: (boolean);
});