"""add_broadcast_table

Revision ID: 4dc4129c77d4
Revises: 20260716_1010
Create Date: 2026-07-16 17:07:08.297746

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4dc4129c77d4'
down_revision = '20260716_1010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text_uz', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=False),
    sa.Column('text_ru', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=False),
    sa.Column('photo_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('target_region_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_status'), 'broadcast', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broadcast_status'), table_name='broadcast')
    op.drop_table('broadcast')
    # ### end Alembic commands ###
